// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcHuWqYmCn9DQLY5FQoE5nw2un5-eoy98',
    appId: '1:759191366726:web:09d6688048a8692be1ee47',
    messagingSenderId: '759191366726',
    projectId: 'clinco-12950',
    authDomain: 'clinco-12950.firebaseapp.com',
    storageBucket: 'clinco-12950.firebasestorage.app',
    measurementId: 'G-1RMCN848Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2j4UCM5wadopUKY6UFWdfpF3IcnLjS3E',
    appId: '1:759191366726:android:fec98cb75ea67e0fe1ee47',
    messagingSenderId: '759191366726',
    projectId: 'clinco-12950',
    storageBucket: 'clinco-12950.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJBanrGT9aCRONyke-nysj2J-W8WsZOWI',
    appId: '1:759191366726:ios:113cb16138aca637e1ee47',
    messagingSenderId: '759191366726',
    projectId: 'clinco-12950',
    storageBucket: 'clinco-12950.firebasestorage.app',
    iosBundleId: 'com.example.projectAzfh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJBanrGT9aCRONyke-nysj2J-W8WsZOWI',
    appId: '1:759191366726:ios:113cb16138aca637e1ee47',
    messagingSenderId: '759191366726',
    projectId: 'clinco-12950',
    storageBucket: 'clinco-12950.firebasestorage.app',
    iosBundleId: 'com.example.projectAzfh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcHuWqYmCn9DQLY5FQoE5nw2un5-eoy98',
    appId: '1:759191366726:web:841829591e4a75cfe1ee47',
    messagingSenderId: '759191366726',
    projectId: 'clinco-12950',
    authDomain: 'clinco-12950.firebaseapp.com',
    storageBucket: 'clinco-12950.firebasestorage.app',
    measurementId: 'G-H45V74T684',
  );
}
